ignore:
  - "src/main/java/com/topup/services/telephone/domain/model/"
  - "src/main/java/com/topup/services/common/repository/MobileNumber.java"
  - "src/main/java/com/topup/services/user/domain/model/"
  - "src/main/java/com/topup/services/common/exception/"
  - "src/main/java/com/topup/services/web/exception"
  - "src/main/java/com/topup/services/config"